### PR TITLE
Integrate feeds of some popular websites * Solved * #9

### PR DESCRIPTION
**Pull request by iknityanand**
## Description
Added Feeds from popular sites maintaining the existing code.

## Related Issue
Integrate feeds of some popular websites. #9

## Motivation and Context
This is a new feature allowing to view feeds from more than one site.

## How Has This Been Tested?
working on my local pc tested with merging the base branch no conflicts.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by manaswinidas** [comment]
@iknityanand Should I merge it? Or there any changes to be made.

**Comment by Asutosh989** [comment]
@iknityanand Should I merge it or is there any changes required?

**Comment by Asutosh989** [comment]
Hi @iknityanand , I was going through the changes. I keep getting an error as follows:

> (node:9268) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: Remote server did not respond with a feed

**Comment by iknityanand** [comment]
image
can you tell me when does this happen? so I can fix it. pls, check the attached image it seems to be working fine at my end.

**Comment by Asutosh989** [comment]
I have checked it. The error seems to internet related  issue which seems to be resolved. I am merging it.

**Pull request merged**
